version: "3.6"

services:
  api:
    build:
      context: ./packages/api
    command: yarn dev
    volumes:
      - /workspaces/bobarr/packages/api:/usr/src/app
      - api_node_modules:/usr/src/app/node_modules
      - api_build:/usr/src/app/dist
    ports:
      - 3001:3001

  web:
    build:
      context: ./packages/web
    command: yarn dev
    volumes:
      - /workspaces/bobarr/packages/web:/usr/src/app
      - web_node_modules:/usr/src/app/node_modules
      - web_build:/usr/src/app/.next
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=development
      - NEXT_TELEMETRY_DISABLED=1
      - WEB_UI_API_URL=http://localhost:4000/graphql

  postgres:
    ports:
      - 5432:5432

  redis:
    ports:
      - 6379:6379
