version: "3.6"

services:
  workspace:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bobarr-workspace
    # Workspace volume is managed by devcontainer.json workspaceMount
    command: sleep infinity
    user: vscode
    volumes:
      - ${localWorkspaceFolder:-.}:/workspaces/bobarr:cached
      - /var/run/docker.sock:/var/run/docker-host.sock:rw
    environment:
      - NODE_ENV=development
      - DOCKER_HOST=unix:///var/run/docker-host.sock
    working_dir: /workspaces/bobarr
    ports:
      - 3001:3001
    networks:
      - default

  # Modify existing services to work better with devcontainer
  api:
    volumes:
      - /workspaces/bobarr/library:/usr/library
    depends_on:
      - postgres
      - redis

  web:
    depends_on:
      - api

  # Make sure data persists
  postgres:
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=bobarr
      - POSTGRES_PASSWORD=bobarr
      - POSTGRES_DB=bobarr

  redis:
    environment:
      - REDIS_PASSWORD=bobarr